### ISSUE TITLE
Truncating of the crmbs generated

### ISSUE THREAD

**Issue by santoshbt** [roidrage/crumble#17]
Hi,  I need to truncate the crumb strings generated to some letters, I am using truncate method, but it does'nt seem to be working properly for me if I put anywhere in breadcrumbs_helper, where we are returning the crumbs. I am using it something like this truncate(name, :length=>10, :ommission=>'...'). Can you please provide me any solution.

For Ex: home // Search me - abcd...

So if the dynamic string generated is "abcdefg", then I want to display "abcd...", So to display this we need to have truncate method on the dynamic value.

**Comment by roidrage** [comment]
Could you be a bit more specific as to where you put truncate in the helper and in what way it didn't work?

**Comment by santoshbt** [comment]
I want to generate a breadcrumb of this kind. Home // CR Track // Edit Track - My New Home in New York,  where the string 'My New Home in New York', is coming from DB, Now I don't want to display the whole string, because of some layout issue. if display fully. So I want to truncate it to some letters followed by dots(...). 

 Ex: Home // CR Track // Edit Track - My New ...

  Now as I have internationalization, in initializers, breadcrumbs.rb , I have passed the crumb as                                         crumb :edit_track, {:title => {:cr_track => :title}}, :edit_cr_track_path, :params => :id

and in en.yml I have put  
breadcrumbs:
    cr_tracks: "Real Cost"
    edit_track: "Edit Real Cost-{{title}}"

I am getting the dynamic value perfectly, but not able to put the truncate method anywhere.

I am trying in crumble/app/helpers/breadcrumbs_helper.rb to put this method truncate(name, :length=>10, :ommission=>'...')., wherever we are returning crumb.name, in the  method of assemble_crumb_title, and so on.

**Comment by roidrage** [comment]
And did adding the truncate in the helper not work properly? That's the place where I'd put it too.

**Comment by santoshbt** [comment]
Well, I have tried putting in helper. But does'nt seem to be working perfectly. Any way I will be checking , and if you find anything please let me know.

**Comment by roidrage** [comment]
I'd try putting it in here: https://github.com/mattmatt/crumble/blob/master/app/helpers/breadcrumbs_helper.rb#L92-104

`assemble_crumble_title` looks like the right place to put it.

**Comment by santoshbt** [comment]
I am trying there by putting and truncate method, it throws translation missing error. Now tracing all the methods to get that dynamically generated string and put there. In calculate_breadcrumb_trail(trail) this method,                                                if not Breadcrumb.instance.last_crumb_linked? and crummy == trail.last  
        breadcrumb_trail << eval(%Q{"#{assemble_crumb_title(crumb)}"})  , I can get the last trail, "Edit Track - My New Home in New York",  but I need my string("My New Home in New York") from database only, where I can put truncate method. So can you help me out in this.

**Comment by roidrage** [comment]
Could you please show me the exact code you're using with an example? I'm having some difficulties to understand what it is you're after.

**Comment by santoshbt** [comment]
I have put the truncate method in assemble_crumb_title, for i18n_params[key], and it seems to be working fine now. thanks.
