### ISSUE TITLE
Unable to load "crumble" via gem or script/plugin install methods.

### ISSUE THREAD

**Issue by makuchaku** [roidrage/crumble#8]
Hi,

I followed the Readme on Github to install Crumble via gem, added configuration, initializers - but the script/server failed to load the gem. I also confirmed this via script/console. I even tried the script/plugin install method.

I can confirm that the gem was installed in /usr/lib/ruby/gems/1.8/gems/crumble-0.1.2.

I'm running 
Gem - 1.3.7
Rails - 2.3.5
OS - Ubuntu

Thanks for such an awesome gem :)
## 

Maku

**Comment by makuchaku** [comment]
The Error I get on script/console is 

<pre>
>> require "crumble"
MissingSourceFile: no such file to load -- crumble
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
    from /usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in `new_constants_in'
    from /usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
    from (irb):1
</pre>

**Comment by roidrage** [comment]
There is no file crumble.rb, you need to require 'breadcrumbs. When installed as a plugin, that should happen automatically.

**Comment by makuchaku** [comment]
Thanks, that fixes it.
